
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "Ext": "touch/src",
  "Ext.data.ProxyMgr": "touch/src/app/Application.js",
  "Ext.device.Purchases.Product": "touch/src/device/purchases/Sencha.js",
  "Ext.device.Purchases.Purchase": "touch/src/device/purchases/Sencha.js",
  "Ext.device.SQLite.Database": "touch/src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLResultSet": "touch/src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLResultSetRowList": "touch/src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLTransaction": "touch/src/device/sqlite/Sencha.js",
  "Ext.draw.engine.SvgContext.Gradient": "touch/src/draw/engine/SvgContext.js",
  "Users": "app",
  "Users.store.Users": "app/store/Users.js"
});
Ext.ClassManager.addNameAlternateMappings({
  "Users.controller.Main": [],
  "Users.model.User": [],
  "Users.store.Users": [],
  "Users.view.CapturePicture": [],
  "Users.view.Main": [],
  "Users.view.UserForm": [],
  "Users.view.UsersList": []
});
Ext.ClassManager.addNameAliasMappings({
  "Users.controller.Main": [],
  "Users.model.User": [],
  "Users.store.Users": [
    "store.users"
  ],
  "Users.view.CapturePicture": [
    "widget.capturepicture"
  ],
  "Users.view.Main": [
    "widget.main"
  ],
  "Users.view.UserForm": [
    "widget.userform"
  ],
  "Users.view.UsersList": [
    "widget.userslist"
  ]
});
